blank_issues_enabled: false
contact_links:
  - name: "\U0001F4E7 Discussions"
    url: https://github.com/chainainexus/can20/discussions/categories/general
    about: General discussions and request help from the community
